version: '3.9'
services:
  mongo:
    image: mongo:latest
    container_name: fitness_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: fitness_backend
    restart: always
    ports:
      - "3001:3000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/fitness-app
    volumes:
      - ./backend/src:/app/src
      - ./backend/package.json:/app/package.json
      - ./backend/tsconfig.json:/app/tsconfig.json
      - /app/node_modules
    command: npm run start:dev
    depends_on:
      - mongo

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: fitness_frontend
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/package.json:/app/package.json
      - ./frontend/tsconfig.json:/app/tsconfig.json
      - /app/node_modules
    command: npm run dev
    depends_on:
      - backend

volumes:
  mongo_data:
