FROM node:22-alpine3.20

WORKDIR /app

# Copy package.json và package-lock.json
COPY package*.json ./
RUN npm install --production

# Rebuild bcrypt để native module tương thích container
RUN npm rebuild bcrypt --build-from-source

# Copy toàn bộ source code
COPY . .

# Build dự án NestJS
RUN npm run build

EXPOSE 3000

CMD ["npm", "run", "start:prod"]