FROM node:22-alpine3.20

WORKDIR /app

# Copy package.json và package-lock.json
COPY package*.json ./
RUN npm install

# Rebuild bcrypt để native module tương thích container
RUN npm rebuild bcrypt --build-from-source

# Copy toàn bộ source code
COPY . .

EXPOSE 3000

# CMD mặc định không cần thiết vì chúng ta sẽ override command trong docker-compose
CMD ["npm", "run", "start:dev"]

# Test git